name = "CTDirect"
uuid = "790bbbee-bee9-49ee-8912-a9de031322d5"
authors = ["Olivier Cots <olivier.cots@enseeiht.fr>"]
version = "0.1.3"

[deps]
ADNLPModels = "54578032-b7ea-4c30-94aa-7cbd1cce6c9a"
CTBase = "54762871-cc72-4466-b8e8-f6c8b58076cd"
NLPModelsIpopt = "f4238b75-b362-5c4c-b852-0801c9a21d71"

[compat]
ADNLPModels = "0.5"
CTBase = "0.4"
NLPModelsIpopt = "0.10"
julia = "1.8"
